blog/urls.py
from django.urls import path
from . import views

app_name="blog" #Works as namespace

urlpatterns = [
    path('', views.blogs, name="blog"),
    path('<int:blog_id>', views.detail, name="detail")
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.home, name="home"),
]

blog/models.py
from django.db import models

# Create your models here.
class Blog(models.Model):
    """
    Represents a project model in home page.
    """
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=150)
    date = models.DateField()
    
    def __str__(self):
        return self.title

website/models.py
from django.db import models

class Project(models.Model):
    """
    Represents a project model in home page.
    """
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=150)
    action_url = models.URLField(blank=True) 
    image = models.ImageField( upload_to="website/images", max_length=None)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog

def blogs(request):
    blogs = Blog.objects.order_by('-date')[:5]
    count = blogs.count
    return render(request,"blog/blog.html",{
        'blogs':blogs,
        'count':count
    })

def detail(request, blog_id):
    blog = get_object_or_404(Blog,pk=blog_id)
    return render(request,"blog/detail.html",{
        "blog": blog
    })

website/views.py
from django.shortcuts import render
from .models import Project

app_name="website"

def home(request):
    projects = Project.objects.all()
    return render(request,"website/home.html",{"projects": projects})

blog/templates/blog/blog.html
{% extends 'website/base.html' %}

{% block body %}
<div class="d-flex justify-content-center" style="color: crimson;">
    <h1 style="padding: 20dp;">I have written {{count}} blog{{count|pluralize}}</h1>
</div>

<div class="jumbotron">
    {% for blog in blogs %}
    <div>
        <a href="{% url 'blog:detail' blog.id %}" style="color: blue;"><h3>{{blog.title}}</h3></a>
        <p>{{blog.description|striptags|truncatechars:100}}</p>
        <p>{{blog.date|date:'M d Y'|upper}}</p>
    </div>
{%endfor%}

</div>
{% endblock body %}

blog/templates/blog/detail.html
{% extends 'website/base.html' %}

{% block body %}
<div class="d-flex justify-content-center">
    <h1>{{blog.title}}</h1>
</div>
<div class="d-flex justify-content-center">
    <h3>{{blog.date|date:'M d Y'}}</h3>
</div>
<div class="d-flex justify-content-center">
    <h3>{{blog.description|safe}}</h3>
</div>
{% endblock body %}

website/templates/website/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Lazy Guide</title>
    <link rel="stylesheet" type="text/css" href="{% static 'website/styles.css' %}">
    <link rel="shortcut icon" href="{% static 'website/favicon.png' %}" type="image/png">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
</head>

<body style="padding-bottom: 50px;">
    <!-- <nav class="navbar navbar-expand navbar-dark bg-dark">
        <ul class="nav navbar-nav">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% static 'website/resume.pdf'%}">Resume</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:blog' %}">Blogs</a>
            </li>
        </ul>
    </nav> -->
    <nav class="nav">
        <div class="container container-nav">
            <div class="header">
                <a href="https://github.com/minielectron" class="header">Prakash Sharma</a>
            </div>
        </div>
    </nav>

    {% block body %}
    {% endblock %}
</body>

</html>

website/templates/website/home.html
{% extends 'website/base.html' %}
{% block body %}
<div class="container">
    <!-- <h2 class="pt-5">My Portfolio</h2> -->
    {% load static %}
    <div class="row pt-2 pb-2 aligner">
        <div class="col-6 col-md-4">
            <a href="https://github.com/minielectron">
                <img class="round" src="{% static 'website/me.jpg'%}" alt="My picture" title="Prakash sharama"
                    height="50%" width="50%" />
            </a>
        </div>
        <div class="col-6 col-md-6">
            <h6 style="color:rgb(138, 138, 138);"><span style="color:black;font-weight: bold;">Hi, I'm Prakash Sharma.</span> <br>I'm an expert android
                application
                and website developer, checkout my awesome projects.</h6>
        </div>
    </div>
</div>
<div class="container" style="margin-top: 20px;">
    <div class="row">
        {% for project in projects %}
        <div class="col-4">
            {% if project.action_url %}
            <h1>{{project.title}}</h1>
            <p>{{project.description|truncatechars:100 }}</p>
            <a href="{{project.action_url}}" target="_blank">
                <img src="{{project.image.url}}" height="150px" width="300px" } />
            </a>
            {% else %}
            <img src="{{project.image.url}}" height="150px" width="300px" />
            {% endif %}
        </div>
        {% endfor %}
    </div>
</div>
{% endblock body %}